name: C/C++ CI

on:
  push:
    branches: [ "main" , "tests" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile_and_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: check gcc version
      run: gcc --version
    - name: compile analyseur_lexical
      run: gcc ./main_test_analyseur_lexical.c ./analyseur_lexical.c -o test_analyseur_lexicale.exe
    - name: test analyseur_lexical
      run: ./test_analyseur_lexicale.exe
    - name: compile analyseur_syntaxique
      run: gcc ./main_test_analyseur_syntaxique.c ./analyseur_syntaxique.c -o test_analyseur_syntaxique.exe
    - name: test analyseur_syntaxique
      run: ./test_analyseur_syntaxique.exe
    - name: compile evaluateur
      run: gcc ./main_test_evaluateur.c ./evaluateur.c -o test_evaluateur.exe
    - name: test evaluateur
      run: ./test_evaluateur.exe
    - name: compile afficheur
      run: gcc ./main_test_afficheur.c ./afficheur.c -o test_afficheur.exe
    - name: test afficheur
      run: ./test_afficheur.exe
    - name: compile main.c
      run: gcc ./main.c -o main.exe
    - name: run main.c
      run: ./main.exe
