name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup compiler:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: check gcc version
      run: gcc --version
